name: Employee api deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package

      - name: Build Docker
        run: docker build -t employee-api-image .

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev

      - name: Tag Image
        run: docker tag employee-api-image asia-south2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/employee-api-repo/employee_api_image:latest

      - name: Push Image
        run: docker push asia-south2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/employee-api-repo/employee_api_image:latest

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials employee-api-cluster --zone asia-south2-b --project employee-project-495713

      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic mysql-secret --from-literal=username=${{ secrets.SPRING_DATASOURCE_USERNAME }} --from-literal=password=${{ secrets.SPRING_DATASOURCE_PASSWORD }} --from-literal=url=${{ secrets.SPRING_DATASOURCE_URL }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/employee_api_image employee_api_image=asia-south2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/employee-api-repo/employee_api_image:latest
